### ISSUE TITLE
AttributeError: 'module' object has no attribute 'caa'

### ISSUE THREAD

**Issue by carnager** [rlhelinski/musicbrainz-catalog#72]
carnager@caprica ~/musicbrainz-catalog > python2 mbcat-cmd.py   
Traceback (most recent call last):
  File "mbcat-cmd.py", line 19, in <module>
    prefs = mbcat.userprefs.PrefManager()
  File "/home/carnager/musicbrainz-catalog/mbcat/userprefs.py", line 26, in __init__
    self.save()
  File "/home/carnager/musicbrainz-catalog/mbcat/userprefs.py", line 80, in save
    'caa_hostname':musicbrainzngs.caa.hostname})
AttributeError: 'module' object has no attribute 'caa'

**Comment by rlhelinski** [comment]
Ah, OK. Failure of this initial call to save should not be fatal and so we
should put it in a try/catch block. It looks like the root cause is
differences in versions of musicbrainz-ngs. What revision are you using?

**Comment by carnager** [comment]
It's version 0.5

**Comment by rlhelinski** [comment]
OK, I am developing this software against 0.6dev. I'll try to see how hard it would be to get the code working with version 0.5, but could you clone the latest from the musicbrainzngs 'master' branch? Here's a link for a zip file: https://github.com/alastair/python-musicbrainzngs/archive/master.zip
